language: rust
services: docker
sudo: required
cache: cargo

# This is required for coveralls
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      
      # Actual sans dependencies
      - libv4l-dev
    sources:
      - kalakris-cmake

# This is a pretty big hack and only really needed on the first of a build chain
before_script:
  - (cargo install cargo-travis | true) && export PATH=$HOME/.cargo/bin:$PATH

# Build, test, benchmark, document. Gogogogo!
script:
  - |
    # Firstly build sans-core by itself
    (cd sans-core && cargo build --verbose --all) &&
    (cd sans-core && cargo test --verbose --all) &&
    (cd sans-core && cargo bench --all) &&
    (cd sans-core && cargo doc) &&
    # Build sans-server
    (cd sans-server && cargo build --verbose --all) &&
    (cd sans-server && cargo test --verbose --all) &&
    (cd sans-server && cargo bench --all) &&
    (cd sans-server && cargo doc) &&
    # Build sans-worker
    (cd sans-worker && cargo build --verbose --all) &&
    (cd sans-worker && cargo test --verbose --all) &&
    (cd sans-worker && cargo bench --all) &&
    (cd sans-worker && cargo doc) &&
    # Clippy checking
    (cd sans-server && cargo test --all --features nightly) &&
    (cd sans-server && cargo clippy --all -- -D warnings) &&
    # Do a formatter run
    cargo fmt --all -- --write-mode=diff

matrix: # additional tests
  include:

  # Rolling compilation for rocket
  - rust: nightly-2018-04-30
    env: RUSTFMT=yes_please
    install: rustup component add rustfmt-preview

# Upload the whole mess
after_success:
  - cargo coveralls --verbose

# AND GOD DAMN IT LET ME SLEEP!
notifications:
  email:
    on_success: never
    on_failure: never
