[package]
name = "sans-server"
version = "0.1.0"
authors = ["Katharina Sabel <katharina.sabel@asquera.de>"]

[dependencies]
sans-core = { path = "../sans-core" }
sans-types = { path = "../sans-core/sans-types/" }
clap = "2.0"

rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
