[package]
name = "sans-server"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
sans-core = { path = "../sans-core" }
sans-types = { path = "../sans-core/sans-types/" }
clap = "2.32"

rocket = "0.4"
rocket_codegen = "0.4"
rocket_contrib = "0.4"
