[package]
name = "sans"
version = "0.1.0"
edition = "2021"
description = "Native Sans touchscreen application"

[dependencies]
clap = { version = "4", features = ["derive"] }
eframe = { version = "0.36.1", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "glow",
    "wayland",
    "x11",
] }
sans-core = { path = "../sans-core" }
