[package]
name = "sans-core"
description = "A comprehensive software for running camera enabled workflows, including Libreflip"
edition = "2021"
version = "0.1.0"

[dependencies]
# Serialisation/ Deserialisation
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"
thiserror = "2"

# Hardware bindings
serialport = "4"

# hw_diag diagnostic CLI
clap = { version = "4", features = ["derive"] }
csv = "1"
chrono = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
rscam = "0.5"

[dev-dependencies]
tempfile = "3"
